### ISSUE TITLE
Events Page - Meta Ticket for adding more related content to view (from 1884)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/test9-lux-frontend#239]
Problem Definition: The events pages are not showing all the available related data that they could be showing using existing HAL links

Expected Behavior: Show all possible relationships on events for improved discovery

BLOCKED by tickets below, plus corresponding HAL link tickets yet to be added. 

Needed

- [x] wireframe
- [x] Review by dev team
- [x] Revisions if needed

Wireframe is too long to screenshot well so can be viewed here: https://nj46vq.axshare.com/?id=g4ubgg&p=entity_-_event_-_oct_23
<img width="594" alt="image" src="https://git.yale.edu/storage/user/2590/files/3812a672-fc0e-4ea1-be5c-
<img width="604" alt="image" src="https://git.yale.edu/storage/user/2590/files/daa3c454-6ce3-48ab-b482-633099bb407b">

Related Tickets: 
- [ ] https://git.yale.edu/lux-its/lux-web/issues/400
- [ ] https://git.yale.edu/lux-its/lux-web/issues/401
- [ ] https://git.yale.edu/lux-its/lux-web/issues/376
- [ ] https://git.yale.edu/lux-its/lux-web/issues/403
- [ ] https://git.yale.edu/lux-its/lux-web/issues/1890
