### ISSUE TITLE
Advanced Search improvements (from 1928)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/test9-lux-frontend#248]
Meta ticket for Advanced Search Improvements.  This ticket should be promoted to dev board along with all the other related tickets, when prepared. 

- https://git.yale.edu/lux-its/lux-web/issues/1892
- https://git.yale.edu/lux-its/lux-web/issues/1801
- Note UAT comments on https://git.yale.edu/lux-its/marklogic/issues/1097

Needed:

- [ ] Tickets above formed
- [ ] Requirements approved by Core and Dev Teams
- [ ] Requirements reviewed with Interactions
- [ ] Further tickets added/connected here

Requirements:
https://app.smartsheet.com/sheets/HhQC82P9vXGM5pXj96824Hq6ggH385RW2635G6q1?view=grid
